name: FinTu
favicon: null
layout_spectrum: 0.48396
typography_spectrum: 0.7399
title: FINANTSTURG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f4f1'
    - '#4e4656'
    - '#000000'
    - '#6c8f88'
    - '#00e0d1'
  brandStrength: 0.2328103450126946
  lightness: 0.6468737854156643
  saturation: 0.055236257845535874
  rhythmicContrast: 0.8226472844835371
purpose: []
